
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: adel
    password: mal280404
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
